# Generated by Django 3.2.8 on 2021-11-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletCarsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('combustible', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coche',
            options={'ordering': ['precio']},
        ),
        migrations.RemoveField(
            model_name='coche',
            name='combustible',
        ),
    ]
