# Generated by Django 3.2.8 on 2021-11-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outletCarsApp', '0002_auto_20211114_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='motor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outletCarsApp.motor'),
            preserve_default=False,
        ),
    ]
