# Generated by Django 3.2.8 on 2021-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletCarsApp', '0003_coche_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
