# Generated by Django 3.2.8 on 2021-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletCarsApp', '0004_coche_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='imagen',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
